CREATE DATABASE IF NOT EXISTS aircraft_fleet_db DEFAULT CHARACTER SET utf8 ;

USE aircraft_fleet_db;

CREATE TABLE IF NOT EXISTS aircraft (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    status ENUM("IN_USE", "DESTROY") DEFAULT "IN_USE" NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
